version: "3.9"

services:
  postgres:
    image: postgres:14.2-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - url_shortener_db:/var/lib/postgresql/data
    command: postgres -c 'max_prepared_transactions=0' -c 'fsync=off'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sidekiq:
    build:
      context: .
    image: url_shortener_sidekiq
    volumes:
      - .:/app
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: bundle exec sidekiq

  url_shortener_web:
    build:
      context: .
    image: url_shortener_web_app
    volumes:
      - .:/app:cached
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e development -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
volumes:
  url_shortener_db:
  redis_data:
