version: "3.9"

services:

  postgres:
    image: postgres:14.2
    env_file:
      - .env
    ports: 
      - '5432:5432'
    volumes:
      - url-shortner-app-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - url-shortner-app-redis:/var/lib/redis/data

  app:
    build:
      context: .
    image: url_shortener_app:latest
    volumes:
      - .:/myapp
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e development -p 3000 -b '0.0.0.0'"

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    image: url_shortener_app_worker:latest
    links:
      - postgres
      - redis
    volumes:
      - .:/myapp
    env_file:
      - .env
volumes:
  url-shortner-app-postgres:
  url-shortner-app-redis: