version: "2"
services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - '.env.docker'
  redis:
    image: redis
    expose:
      - "6379"
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: urls_shortener_app:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e development -p 3000 -b '0.0.0.0'"
    env_file:
      - '.env.docker'
    volumes:
      - .:/myapp
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
  rails_worker:
    image: urls_shortener_app:latest
    command: bash -c "bundle exec sidekiq"
    env_file:
      - '.env.docker'
    volumes:
      - .:/myapp
    depends_on:
      - postgres
volumes:
  pgdata:
