# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
default: &default
  adapter: postgresql
  host: <%= ENV["HOST"] %>
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: url_shortner_app_development

test:
  <<: *default
  database: url_shortner_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # port: 5432
  # database: <%= ENV['DATABASE'] %>
  # username: <%= ENV['USERNAME'] %>
  # password: <%= ENV['PASSWORD'] %>
  # host: <%= ENV['DATABASE_URL'] %>
