:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30

:queues:
  - default
# :schedule:
#   HelloWorldWorker:
#     cron: "* * * * *"
#     queue: default
#     enabled: true
